### ISSUE TITLE
Unnecessary files are exist in this project

### ISSUE THREAD

**Issue by springshine0925** [springshine0925/sopa-solana#2]
Text files are unnecessary.
Delete them!.

**Comment by springshine0925** [comment]
You should fork your repository in master1 repository.

**Comment by ShineGo1** [comment]
👋

**Comment by 0129general** [comment]
👋 I'm a full stack developer with 6+ years of experiences. In my current role, I'm focusing on Solona.

Please assign to me it.

**Comment by springshine0925** [comment]
This problem was just fixed today.
